<?php



class SessionVagabond extends SessionHandler {

	public function destroy($id)
	{
		$pdo = \Database::getPdo();
		session_start();
		for (;range($_SESSION['panier']);) {
			$sql = "INSERT INTO panier (id_user, id_product, number) VALUES (:id_user, :id_product, :number)";
			$query = $pdo->prepare($sql);
			$query->execute(['id_user' => $_SESSION['id_user'], 'id_product' => $_SESSION['panier']['id_product'], 'number' => $_SESSION['panier']['number']]);
		}
		parent::destroy($id); // TODO: Change the autogenerated stub
	}
}